# SPDX-FileCopyrightText: 2016-2018 CERN.
# SPDX-FileCopyrightText: 2026 Graz University of Technology.
# SPDX-License-Identifier: MIT

"""Severity and run status choice types migration."""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

from invenio_checks.models import CheckRunStatus, Severity

# revision identifiers, used by Alembic.
revision = "1777225247"
down_revision = "1773672705"
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "checks_config",
        "severity",
        existing_type=sa.VARCHAR(length=1),
        type_=sqlalchemy_utils.types.choice.ChoiceType(
            Severity, impl=sa.CHAR(length=1)
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "checks_run",
        "status",
        existing_type=sa.VARCHAR(length=1),
        type_=sqlalchemy_utils.types.choice.ChoiceType(
            CheckRunStatus, impl=sa.CHAR(length=1)
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "checks_run",
        "status",
        existing_type=sqlalchemy_utils.types.choice.ChoiceType(
            CheckRunStatus, impl=sa.CHAR(length=1)
        ),
        type_=sa.VARCHAR(length=1),
        existing_nullable=False,
    )
    op.alter_column(
        "checks_config",
        "severity",
        existing_type=sqlalchemy_utils.types.choice.ChoiceType(
            Severity, impl=sa.CHAR(length=1)
        ),
        type_=sa.VARCHAR(length=1),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
