#
# This file is part of Invenio.
# Copyright (C) 2016-2018 CERN.
#
# Invenio is free software; you can redistribute it and/or modify it
# under the terms of the MIT License; see LICENSE file for more details.

"""Severity and run status choice types migration."""

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op

from invenio_checks.models import CheckRunStatus, Severity

# revision identifiers, used by Alembic.
revision = "1777225247"
down_revision = "c39b06b59667"
branch_labels = ()
depends_on = None


def upgrade():
    """Upgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "checks_config",
        "severity",
        existing_type=sa.VARCHAR(length=1),
        type_=sqlalchemy_utils.types.choice.ChoiceType(
            Severity, impl=sa.CHAR(length=1)
        ),
        existing_nullable=False,
    )
    op.alter_column(
        "checks_run",
        "status",
        existing_type=sa.VARCHAR(length=1),
        type_=sqlalchemy_utils.types.choice.ChoiceType(
            CheckRunStatus, impl=sa.CHAR(length=1)
        ),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    """Downgrade database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "checks_run",
        "status",
        existing_type=sqlalchemy_utils.types.choice.ChoiceType(
            CheckRunStatus, impl=sa.CHAR(length=1)
        ),
        type_=sa.VARCHAR(length=1),
        existing_nullable=False,
    )
    op.alter_column(
        "checks_config",
        "severity",
        existing_type=sqlalchemy_utils.types.choice.ChoiceType(
            Severity, impl=sa.CHAR(length=1)
        ),
        type_=sa.VARCHAR(length=1),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
